export const EMPTY_FORM = {
  fullName: '',
  dateOfBirth: '',
  placeOfBirth: '',
  gender: '',
  nationality: '',
  passportNumber: '',
  dateOfIssuance: '',
  dateOfExpiry: '',
  vietnameseAddress: '',
  phoneNumber: '',
  email: '',
  emergencyContactName: '',
  emergencyContactRelationship: '',
  emergencyContactPhone: '',
  emergencyContactEmail: '',
  signature: '',
  signatureDate: '',
};
